#!/usr/bin/env sh

readonly HYPRLAND_SOCKET2="$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock"

activateNotifications() { swaync-client -df > /dev/null; }
deactivateNotifications() { swaync-client -dn > /dev/null; }

main() {
  isCurrentWorkspaceFullscreen="$(hyprctl -j activeworkspace | jq -r '.hasfullscreen')"
  isNotificationsDeactivated="$(swaync-client -D)"
  
  if [ "$isCurrentWorkspaceFullscreen" = true ] && [ "$isNotificationsDeactivated" = false ]; then
       deactivateNotifications
  elif [ "$isCurrentWorkspaceFullscreen" = false ] && [ "$isNotificationsDeactivated" = true ]; then
        activateNotifications
  fi
}

if [ -z "$HYPRLAND_INSTANCE_SIGNATURE" ]; then
  echo "Error: HYPRLAND_INSTANCE_SIGNATURE could not be determined."
  echo "Ensure Hyprland is running and try again."
  exit 1
fi

while true; do
  socat - "UNIX-CONNECT:$HYPRLAND_SOCKET2" | while read -r socatOutput; do 
    if echo "$socatOutput" | grep -Eq '(^fullscreen|^workspace)'; then
         main 
     fi
  done
done
